version: '3.8'
services:
  db:
    container_name: local_pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fni_service
      PGDATA: /var/lib/postgresql/data
    user: "${UID}:${GID}"
    volumes:
       - /Users/priyadarshanp/postgresDevLimaV2:/var/lib/postgresql/data
    ports:
      - "5432:5432"